FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["Directory.Build.props", "./"]
COPY ["src/OrderService/OrderService.csproj", "OrderService/"]
COPY ["src/Common/Loft.Common/Loft.Common.csproj", "Common/Loft.Common/"]

RUN dotnet restore "OrderService/OrderService.csproj"

COPY ["src/Common/Loft.Common/", "Common/Loft.Common/"]
COPY ["src/OrderService/", "OrderService/"]

WORKDIR /src/OrderService

RUN dotnet build "OrderService.csproj" -c $BUILD_CONFIGURATION -o /app/build
RUN dotnet publish "OrderService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "OrderService.dll"]
